---
- name: install cassandra gpg key
  apt_key: url='http://pgp.mit.edu/pks/lookup?op=get&search=0x{{ cassandra_gpg_key_id }}' state=present

- name: add cassandra deb repository
  apt_repository: repo='deb http://www.apache.org/dist/cassandra/debian {{ cassandra_series_version }} main' state=present

- name: add cassandra deb sources repository
  apt_repository: repo='deb-src http://www.apache.org/dist/cassandra/debian {{ cassandra_series_version }} main' state=present

- name: install cassandra packages
  apt: pkg={{ item }} state=latest update_cache=yes force=yes
  with_items:
      - openjdk-7-jre-headless
      - cassandra
  notify: restart cassandra

- name: copy cassandra conf
  template: src=cassandra.yaml.j2 dest=/etc/cassandra/cassandra.yaml
  notify: reload cassandra
